version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: "ons-db"
    environment:
      POSTGRES_ROOT_PASSWORD: "UKFZoaJh!Pddx9TP.UUV"
      POSTGRES_DATABASE: "ons"
      POSTGRES_USER: "ons"
      POSTGRES_PASSWORD: "fqdeZRkKRLhWpcLB9y9D"
      
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: "ons-backend"
    depends_on:
      - db
    ports:
      - 8000:8000

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: "ons-frontend"
    environment:
      BACKEND_HOST: "backend:8000"
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ./frontend/build:/app/serve-folder