version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: "ons-db"
    environment:
      POSTGRES_ROOT_PASSWORD: "UKFZoaJh!Pddx9TP.UUV"
      POSTGRES_DATABASE: "ons"
      POSTGRES_USER: "ons"
      POSTGRES_PASSWORD: "fqdeZRkKRLhWpcLB9y9D"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      ons:
        ipv4_address: 10.10.13.10
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ons" ]

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: "ons-backend"
    depends_on:
      - db
    environment:
      DATABASE_HOST: "db"
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend
        read_only: true
    networks:
      ons:
        ipv4_address: 10.10.13.11


  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: "ons-frontend"
    environment:
      BACKEND_HOST: "backend:8000"
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ./frontend/build:/app/serve-folder

networks:
  ons:
    ipam:
      driver: default
      config:
        - subnet: "10.10.13.0/24"
