version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: "ons-postgres"
    environment:
      POSTGRES_ROOT_PASSWORD: "UKFZoaJh!Pddx9TP.UUV"
      POSTGRES_DATABASE: "ons"
      POSTGRES_USER: "ons"
      POSTGRES_PASSWORD: "fqdeZRkKRLhWpcLB9y9D"
    networks:
      ons:
        ipv4_address: 10.10.13.10
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ons" ]
        
  backend:
    image: noebuerki/ons-backend:latest
    container_name: "ons-backend"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/ons/backend/
    ports:
      - "8000:8000"
    depends_on:
      migration:
         condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment: &backend-environment
      DJANGO_DEBUG: true
    networks:
      ons:
        ipv4_address: 10.10.13.11

  migration:
    image: noebuerki/ons-backend:latest
    command: python manage.py migrate --noinput
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      <<: *backend-environment
    networks:
      ons:
        ipv4_address: 10.10.13.11

networks:
  ons:
    ipam:
      driver: default
      config:
        - subnet: "10.10.13.0/24"
