[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "double"

[tool.isort]
force_alphabetical_sort_within_sections = "True"
force_single_line = "True"
from_first = "False"
line_length = 200
lines_after_imports = 2
known_first_party = "ons"
skip = "venv"
