name: CICD Docker Deployment Backend

on:
  push:
    branches: [ main ]
    paths: 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: ./mvnw -B -ntp spring-boot:build-image

      - name: Tag the Docker image
        run: docker tag ons:1.0.0 ${{ secrets.DOCKERHUB_USERNAME }}/ons-backend:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_TOKEN }}

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ons-backend:latest

      - name: Trigger Stack redeploy
        run: |
          curl --location --request PUT -k 'https://portainer.noebuerki-services.ch/api/stacks/9/git/redeploy?endpointId=2' --header 'Content-Type: application/json' --header 'X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}' --data '{
            "PullImage": true,
            "RepositoryAuthentication": true,
            "RepositoryReferenceName": "refs/heads/main"
          }'
