name: CICD Docker Deployment Backend

on:
  push:
    branches: [ main ]
    paths: 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
    
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_TOKEN }}

      - name: Build and Push the Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: backend/Dockerfile
          tags: noebuerki/ons-backend:latest

      - name: Trigger Stack redeploy
        run: |
          curl --location --request PUT -k 'https://portainer.noebuerki-services.ch/api/stacks/1/git/redeploy?endpointId=2' --header 'Content-Type: application/json' --header 'X-API-Key: ${{ secrets.PORTAINER_API_TOKEN }}' --data '{
            "PullImage": true,
            "RepositoryAuthentication": true,
            "RepositoryReferenceName": "refs/heads/main"
          }'
